plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.protobuf' version '0.10.0'
}

group = 'com.bill'
version = '0.0.1-SNAPSHOT'
description = 'streaming'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-grpc-server'
    testImplementation 'org.springframework.boot:spring-boot-starter-grpc-server-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf {
    plugins {
        grpc {}
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
